version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cda
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: python_dw
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: cda
    volumes:
      - .:/app
    command: bash -c "python main.py && python dw.py"
